/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code.forces;

public class App {

    public static void main(String[] args) {
        WayTooLongWords obj = new WayTooLongWords();
        obj.wayTooLongWords();
    }
}
