/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code.forces;

public class App {

    public static void main(String[] args) {
        Watermelon watermelon = new Watermelon();
        watermelon.watermelon();
    }
}
