/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code.forces;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        var obj = new Team();
        System.out.println(obj.team());
    }

}
